"""Remove unused created_at index

Revision ID: 2461ad0a3c7b
Revises: 6e1ac969c307
Create Date: 2026-02-28 01:05:20.886226

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2461ad0a3c7b"
down_revision: Union[str, Sequence[str], None] = "6e1ac969c307"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_code", sa.String(length=6), nullable=False),
        sa.Column("original_url", sa.String(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_urls_short_code"), "urls", ["short_code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urls_short_code"), table_name="urls")
    op.drop_table("urls")
    # ### end Alembic commands ###
